generate_comments = true
blank_lines = true
git_prefix = "https://github.com/MinaProtocol/mina/blob/b14f0da9ebae87acd8764388ab4681ca10f07c89/"
preamble = '#[doc = " Naive implementation for big integer."] pub type BigInt = [u8; 32]; _blank_!();'

[base_types.float]
rust_id = 'f32'
args_num = 'None'

[base_types.kimchi_backend_bigint_32_V1]
rust_id = 'BigInt'
args_num = 'None'

[base_types.unit]
rust_id = '()'
args_num = 'None'

[base_types.option]
rust_id = 'Option'
args_num = 'Single'

[base_types.array]
rust_id = 'Vec'
args_num = 'Single'

[base_types.string]
rust_id = 'String'
args_num = 'None'

[base_types.bool]
rust_id = 'bool'
args_num = 'None'

[base_types.int]
rust_id = 'i32'
args_num = 'None'

[base_types.int32]
rust_id = 'i32'
args_num = 'None'

[base_types.int64]
rust_id = 'i64'
args_num = 'None'

[base_types.list]
rust_id = 'Vec'
args_num = 'Single'
